### PR TITLE
Ensures that the license key is generated using a  cryptographically stronger method

### PR DESCRIPTION
**Pull request by hexmarkrecords**
Hi,

I came across this repository and found it really useful for my needs. I just noticed the use of the pseudo random  Math.random  and there are better random number strategies in node with higher entrophy. 

I put together this PR with some unit tests from my fork, for your consideration.

### CODE REVIEW

**Comment by mcnaveen** [comment]
Hi, @hexmarkrecords I just checked and PR is closed for some reason.

**Comment by hexmarkrecords** [comment]
Sorry deleted the fork. I noticed one small error in my code resultA should be compared to resultB.

**Comment by hexmarkrecords** [comment]
BTW in  >= node 15 there is a handy method crypto.getRandomValues which is similar to that found in the browser so you can do something like this:

`
const crypto = require('crypto').webcrypto;

const generateLicenseKey = (length, pairs = 4) => {
  let result = '';
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  const charactersLength = characters.length;
  
  const array = new Uint32Array(length);
  crypto.getRandomValues(array);

  for (let i = 0; i < length; ++i) {
    result += characters.charAt(array[i] % charactersLength);
  }
  return (result.match(new RegExp(`.{1,${pairs}}`, 'g')) || []).join('-');
};
`

However the one I did in the PR is still compatible with node prior.

**Comment by mcnaveen** [comment]
Ah, Understood. Will check it locally and update you here.

**Comment by mcnaveen** [comment]
@all-contributors please add @hexmarkrecords for code

**Comment by mcnaveen** [comment]
Thanks for your Contribution. @hexmarkrecords :pray: :heart:

**Pull request merged**
